# Generated by Django 5.2.7 on 2025-10-21 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_reporte', models.CharField(choices=[('Voluntario', 'Voluntario'), ('Obligatorio', 'Obligatorio')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'tipos_usuario',
            },
        ),
        migrations.CreateModel(
            name='EstadisticasReporte',
            fields=[
                ('id_estadistica', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('consecuencias', models.TextField(blank=True, null=True)),
                ('severidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fase_ocurrencia', models.CharField(blank=True, max_length=100, null=True)),
                ('otros', models.TextField(blank=True, null=True)),
                ('id_reporte', models.OneToOneField(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, to='api.reporte')),
            ],
            options={
                'verbose_name_plural': 'Estadísticas de Reportes',
                'db_table': 'estadisticas_reportes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.rol')),
                ('id_tipo', models.ForeignKey(db_column='id_tipo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tipousuario')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
        ),
    ]
