# Generated by Django 5.2.7 on 2026-01-21 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_usuario_contrasena_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteVoluntario',
            fields=[
                ('id_reporte', models.OneToOneField(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.reporte')),
                ('nombre_reportante', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_reportante', models.CharField(blank=True, max_length=255, null=True)),
                ('detalles_completos_json', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Detalles de Reportes Voluntarios',
                'db_table': 'reporte_voluntario',
            },
        ),
        migrations.RenameField(
            model_name='reporte',
            old_name='fecha_reporte',
            new_name='fecha_creacion_sistema',
        ),
        migrations.RemoveField(
            model_name='estadisticasreporte',
            name='otros',
        ),
        migrations.RemoveField(
            model_name='reporte',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='estadisticasreporte',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estadisticasreporte',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='estadisticasreporte',
            name='probabilidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reporte',
            name='estatus',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reporte',
            name='fecha_elaboracion',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='numero_reporte_manual',
            field=models.CharField(default='S/N', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte',
            name='subtipo',
            field=models.CharField(choices=[('Voluntario', 'Voluntario'), ('Obligatorio', 'Obligatorio')], default='Voluntario', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reporte',
            name='tipo_reporte',
            field=models.CharField(max_length=50),
        ),
    ]
