# Generated by Django 5.2.7 on 2026-01-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reportevoluntario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportevoluntario',
            name='fecha_evento',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportevoluntario',
            name='hora_local',
            field=models.TimeField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportevoluntario',
            name='lugar',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportevoluntario',
            name='probabilidad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportevoluntario',
            name='severidad',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
