# Generated by Django 5.2.7 on 2026-01-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reportevoluntario_fecha_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadisticasreporte',
            name='fecha_evento',
        ),
        migrations.RemoveField(
            model_name='estadisticasreporte',
            name='lugar',
        ),
        migrations.RemoveField(
            model_name='estadisticasreporte',
            name='probabilidad',
        ),
        migrations.AddField(
            model_name='estadisticasreporte',
            name='otros',
            field=models.TextField(blank=True, null=True),
        ),
    ]
