# Generated by Django 5.2.7 on 2026-01-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_estadisticasreporte_fecha_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id_reporte', models.OneToOneField(db_column='id_reporte', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detalles_reporte', serialize=False, to='api.reporte')),
                ('nombre_reportante', models.CharField(blank=True, max_length=255, null=True)),
                ('correo_reportante', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar', models.CharField(max_length=255)),
                ('hora_local', models.TimeField()),
                ('fecha_evento', models.DateField()),
                ('probabilidad', models.CharField(max_length=50)),
                ('severidad', models.CharField(max_length=50)),
                ('detalles_completos_json', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Detalles de Reportes Generados',
                'db_table': 'reportes_generados',
            },
        ),
        migrations.DeleteModel(
            name='ReporteVoluntario',
        ),
    ]
