"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# core/settings.py
from pathlib import Path
from datetime import timedelta # Importar para configurar la expiración del token

BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-a#5-sq2%sn=!fwkz$jhwwrbrj2)=60(wo6dn-^q0%wdh9dc6sj'
DEBUG = True
ALLOWED_HOSTS = []

# --- Aplicaciones Adicionales ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Terceros
    'corsheaders',            # Para permitir comunicación con Angular
    'rest_framework',         # Para crear la API REST
    'rest_framework_simplejwt', # Para la autenticación JWT
    # Tus apps
    'api',                    # Tu aplicación 'api'
]

# --- Middleware (Agregando CORS) ---
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CORS Headers debe ir antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# --- Database (PostgreSQL) ---
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'SSRA75',
        'USER': 'postgres',
        'PASSWORD': '1978',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation... (dejamos por defecto)
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es-mx' 
TIME_ZONE = 'America/Mexico_City' 
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CAMBIOS CLAVE PARA AUTENTICACIÓN Y API ---

# 1. Especificar el modelo de usuario a utilizar
AUTH_USER_MODEL = 'api.Usuario' # <-- Utiliza tu modelo Usuario

# 2. Configuración CORS (Ajusta el puerto de tu Angular)
CORS_ALLOWED_ORIGINS = [
    'http://localhost:4200',  # Angular default port
    'http://127.0.0.1:4200',
]
# Si necesitas permitir peticiones desde cualquier origen (solo en desarrollo)
# CORS_ALLOW_ALL_ORIGINS = True 

# 3. Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Permite la autenticación basada en tokens JWT para todas las vistas que lo usen
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Recomendable para asegurar los endpoints por defecto
        'rest_framework.permissions.IsAuthenticated', 
    )
}

# 4. Configuración de JWT Simple
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),

    # 1. Especifica la ruta completa a tu Serializer personalizado
    'TOKEN_OBTAIN_SERIALIZER': 'api.serializers_auth.CustomTokenObtainPairSerializer',
    
    # 🚨 2. AJUSTE CLAVE PARA RESOLVER 'AttributeError: id' 🚨
    # Indica a JWT que use tu campo de clave primaria: 'id_usuario'
    'USER_ID_FIELD': 'id_usuario', 
}